#!/bin/bash

set -u

#
# Robert Brockway
#
# 25 February 2023
#
# $1: Hostname
# $2: Filesystem
# $3: Bucket
#

#
# Functions
#

error()
{
	echo "Error: $1"
	logger "Error: $1"

	exit $1
}

initialise()
{
	AWSBIN=/usr/bin/s3cmd
	AWSCFG=~/.s3cfg

	command -v $AWSBIN &> /dev/null
	case $? in
	0)
		true
		;;
	*)
		error 40
		;;
	esac

	if [ -f $AWSCFG ]
	then
		true
	else
		error 45
	fi

	APPNAME="$(basename $0)"

	STAGING=/srv/staging

	TIMESTAMP=$(date +%s)

	TARFILE=$HOST.$FILESYSTEM.$TIMESTAMP.$$.tar

	echo "Backing up filesystem /$FILESYSTEM on $HOST"
}

backupToS3()
{
	case $S3 in
	yes)
		echo "Backing up to S3"
		s3cmd put $STAGING/$TARFILE s3://$BUCKET/$HOST/$FILESYSTEM/ &> /dev/null
		case $? in
		0)
			rm -f $STAGING/$TARFILE
			;;
		*)
			error 90
			;;
		esac
		;;
	no)
		echo "No bucket specified so not backing up to S3"
		;;
	*)
		# This shouldn't happen
		error 95
		;;
	esac
}

remoteBackup()
{
	echo "Creating tar file"
    ssh root@$HOST tar --warning=no-file-changed -cf - /$FILESYSTEM > $STAGING/$TARFILE 2> /dev/null
	# Certain errors are ok
	# Once I have that nailed down I can re-enable this
        #case $? in
        #0)
        #        true
        #        ;;
        #*)
        #        error 50
        #        ;;
        #esac
}

splitBackup()
{
	echo "Splitting tar file"
	if [ -f $STAGING/$TARFILE ]
	then
		split -b 10G $STAGING/$TARFILE $TARFILE.
		case $? in
		0)
			true
			;;
		*)
			error 70
			;;
		esac
	fi
}

#
# Main
#

case ${1-""} in
	"")
        error 11
		;;
	*)
		HOST=$1
		;;
esac

case ${2-""} in
	"")
        error 12
		;;
	*)
		FILESYSTEM=$2
		;;
esac

case ${3-""} in
	"")
        BUCKET=""
		S3=no
		;;
	*)
		BUCKET=$3
		S3=yes
		;;
esac

initialise
remoteBackup
backupToS3
