###########
# Scripts #
###########

- name: Copy /usr/local/bin/sillyBackup
  copy:           
    src: sillyBackup
    dest: /usr/local/bin/sillyBackup
    owner: root
    group: root
    mode: 0755

- name: Copy /usr/local/bin/sillyBackupAll
  copy:           
    src: sillyBackup
    dest: /usr/local/bin/sillyBackupAll
    owner: root
    group: root
    mode: 0755

########
# Cron #
########

- name: Run sillyBackup
  ansible.builtin.cron:
    user: root
    name: sillyBackup
    hour: "20"
    minute: "*/20+10"
    job: "/usr/local/sbin/ansiblePull rbrockway scripts sillyBackup"
