#!/bin/bash

#
# Robert Brockway
#
# 7 March 2023
#
# $1: Optional host
# $2: Optional filesystem
#

#
# Config
#

BUCKET=avfmbackup
HOSTLIST="castor.opentrend.net pollux.opentrend.net sirius.opentrend.net admin.avoiceformen.com int.avoiceformen.com mon.avoiceformen.com prod.avoiceformen.com"
FSLIST="bin boot dev etc home lib lib64 opt root srv usr var"

#
# Functions
#

backupAll()
{
	for I in $HOSTLIST
	do
		backupOneHost $I
	done
}

backupOneFilesystem()
{
	HOST=$1
	FILESYSTEM=$2
	#sillyBackup $HOST $FILESYSTEM $BUCKET
	/usr/local/bin/sillyBackup $HOST $FILESYSTEM

}

backupOneHost()
{
	HOST=$1
	for J in $FSLIST
	do
		backupOneFilesystem $HOST $J
	done
}

initialise()
{
	# Treat unset variables as an error when substituting.
    set -u
}

#
# Main
#

case $1 in
"")
	initialise
	backupAll
	;;
*)
	case $2 in
	"")
		initialise
		backupOneHost $1
		;;
	*)
		initialise
		backupOneFilesystem $1 $2
		;;
	esac
	;;
esac
